name: Test

on: [push, pull_request]

jobs:
  test:
    name: Run Tests for mirror-bridge-proxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run test
